# Generated by Django 6.0.3 on 2026-04-12 12:46

import datetime
import django.db.models.deletion
import django.utils.timezone
import workouts.enums
import workouts.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "workout_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default=workouts.enums.WorkoutStatus["PLANNED"],
                        max_length=20,
                    ),
                ),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("aerobic", "Aerobic"),
                            ("strength", "Strength"),
                            ("generic", "Generic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AerobicDetails",
            fields=[
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        null=True,
                        validators=[
                            workouts.utils.GreaterThanDurationValidator(
                                datetime.timedelta(0),
                                message="Duration must be greater than 0:00:00.",
                            )
                        ],
                    ),
                ),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "workout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="aerobic_details",
                        serialize=False,
                        to="workouts.workout",
                    ),
                ),
                (
                    "distance",
                    models.PositiveIntegerField(
                        blank=True, help_text="Distance in meters.", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Aerobic details",
            },
        ),
        migrations.CreateModel(
            name="GenericDetails",
            fields=[
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        null=True,
                        validators=[
                            workouts.utils.GreaterThanDurationValidator(
                                datetime.timedelta(0),
                                message="Duration must be greater than 0:00:00.",
                            )
                        ],
                    ),
                ),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "workout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="generic_details",
                        serialize=False,
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Generic details",
            },
        ),
        migrations.CreateModel(
            name="StrengthDetails",
            fields=[
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        null=True,
                        validators=[
                            workouts.utils.GreaterThanDurationValidator(
                                datetime.timedelta(0),
                                message="Duration must be greater than 0:00:00.",
                            )
                        ],
                    ),
                ),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "workout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="strength_details",
                        serialize=False,
                        to="workouts.workout",
                    ),
                ),
                ("num_sets", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total_weight",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total weight in kg.", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Strength details",
            },
        ),
        migrations.CreateModel(
            name="Macrocycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActiveMacrocycle",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "macrocycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.macrocycle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mesocycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(editable=False)),
                (
                    "meso_type",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("prep", "Prep"),
                            ("build", "Build"),
                            ("sharpen", "Sharpen"),
                            ("specific", "Specific"),
                            ("peak", "Peak"),
                            ("transition", "Transition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "macrocycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesocycles",
                        to="workouts.macrocycle",
                    ),
                ),
            ],
            options={
                "ordering": ["macrocycle", "order"],
            },
        ),
        migrations.CreateModel(
            name="Microcycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(editable=False)),
                ("duration_days", models.PositiveSmallIntegerField(default=7)),
                (
                    "micro_type",
                    models.CharField(
                        choices=[
                            ("intro", "Intro"),
                            ("load", "Load"),
                            ("overload", "Overload"),
                            ("consolidate", "Consolidate"),
                            ("deload", "Deload"),
                            ("taper", "Taper"),
                            ("race", "Race"),
                        ],
                        default=workouts.enums.MicrocycleType["LOAD"],
                        max_length=20,
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                (
                    "planned_num_runs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "planned_distance",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total planned distance in meters.",
                        null=True,
                    ),
                ),
                (
                    "planned_long_run_distance",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Planned long run distance in meters.",
                        null=True,
                    ),
                ),
                (
                    "planned_strength_sessions",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "planned_cross_sessions",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "mesocycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microcycles",
                        to="workouts.mesocycle",
                    ),
                ),
            ],
            options={
                "ordering": ["mesocycle", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "parent_type",
                    models.CharField(
                        choices=[
                            ("aerobic", "Aerobic"),
                            ("strength", "Strength"),
                            ("generic", "Generic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gui_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Defines UI inputs (e.g., {'z1_pct': {'type': 'number', 'label': 'Zone 1 %'}})",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workout subtypes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "parent_type"), name="uq_subtype_name_parent"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="workout",
            name="subtype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="workouts.workoutsubtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrocycle",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uq_macro_user_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="mesocycle",
            constraint=models.UniqueConstraint(
                fields=("macrocycle", "order"), name="uq_meso_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="microcycle",
            constraint=models.UniqueConstraint(
                fields=("mesocycle", "order"), name="uq_micro_order"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["user", "-start_time"], name="wrk_user_time_idx"
            ),
        ),
    ]
